import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // Old city URLs (never existed as routes) -> booking search filtered by city
      {
        source: "/explore/cities/:city",
        destination: "/booking/search?city=:city",
        permanent: true,
      },
      // Old category URL with ?type=truck -> booking search filtered by category
      {
        source: "/explore/categories",
        has: [{ type: "query", key: "type", value: "truck" }],
        destination: "/booking/search?category=truck",
        permanent: true,
      },
      // Any other old category URL -> booking search
      {
        source: "/explore/categories/:path*",
        destination: "/booking/search",
        permanent: true,
      },
      {
        source: "/explore/categories",
        destination: "/booking/search",
        permanent: true,
      },
      // Host signup lives on its own subdomain
      {
        source: "/become-a-host",
        destination: "https://host.muvment.ng/",
        permanent: true,
      },
      // Old short blog slug -> current autogenerated slug
      {
        source: "/blog/make-money-with-your-car-nigeria",
        destination:
          "/blog/make-money-with-your-car-in-nigeria-a-realistic-guide-to-hosting-on-muvment-83dzfq",
        permanent: true,
      },
    ];
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "res.cloudinary.com",
      },
    ],
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 31536000,
  },
  compress: true,
  poweredByHeader: false,
};

export default nextConfig;
