import type { Metadata } from "next";
import "./globals.css";
import ClientRoot from "@/components/utils/ClientRoot";

import { Inter } from "next/font/google";
import { QueryProvider } from "@/controllers/connnector/QueryProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={inter.className}>
        <QueryProvider>
          <ClientRoot>{children}</ClientRoot>
        </QueryProvider>
      </body>
    </html>
  );
}
